<?php if (isset($this->_message) and $this->_message['error']<=43) {
  echo "<script type='text/javascript'> window.onload = function() {
    document.getElementById('edita').style.display = 'block';
    document.getElementById('ficha').style.display = 'none';
    document.getElementById('horario').style.display = 'none';
    document.getElementById('afic').classList.remove('active');
    document.getElementById('hora').classList.remove('active');
    document.getElementById('amod').classList.add('active');}
   </script>";
} if (isset($this->_message) and $this->_message['error']==73) {
  echo "<script type='text/javascript'> window.onload = function() {
    document.getElementById('edita').style.display = 'none';
    document.getElementById('ficha').style.display = 'none';
    document.getElementById('horario').style.display = 'block';
    document.getElementById('afic').classList.remove('active');
    document.getElementById('amod').classList.remove('active');
    document.getElementById('hora').classList.add('active');
    }
   </script>";
}
if (isset($this->modalmessage)) { echo
"<script type='text/javascript'> window.onload = function() {
    document.getElementById('edita').style.display = 'none';
    document.getElementById('ficha').style.display = 'none';
    document.getElementById('horario').style.display = 'block';
    document.getElementById('afic').classList.remove('active');
    document.getElementById('amod').classList.remove('active');
    document.getElementById('hora').classList.add('active');
    }
   </script>
<script>
		document.addEventListener('DOMContentLoaded', function() {
  var modal = document.getElementById('exampleModal3');
  var bootstrapModal = new bootstrap.Modal(modal);
  bootstrapModal.show();
});
	</script>";
}
if (isset($this->modalmessage2)) { echo
  "<script type='text/javascript'> window.onload = function() {
      document.getElementById('edita').style.display = 'none';
      document.getElementById('ficha').style.display = 'none';
      document.getElementById('horario').style.display = 'block';
      document.getElementById('afic').classList.remove('active');
      document.getElementById('amod').classList.remove('active');
      document.getElementById('hora').classList.add('active');
      }
     </script>
  <script>
      document.addEventListener('DOMContentLoaded', function() {
    var modal = document.getElementById('".$this->modnum."');
    var bootstrapModal = new bootstrap.Modal(modal);
    bootstrapModal.show();
  });
    </script>";
  }
?>
<style>
  /* Custom CSS for Excel-like table */
  .excel-table {
    border-collapse: collapse;

    /* Remove spacing between table cells */
    width: 100%;
  }

  .excel-table th,
  .excel-table td {
    padding: 4px 8px;
    /* Adjust padding for table cells */
    font-size: 12px;
    /* Adjust font size */
    border: 1px solid #ccc;
    /* Add a border to table cells */
    text-align: left;
    /* Align text to the left */
  }


  .excel-table th {
    background-color: #f2f2f2;
    /* Add a background color to header cells */
    font-weight: bold;
    /* Make header text bold */
  }

  .excel-table tr:nth-child(even) {
    background-color: #f9f9f9;
    /* Alternate row background color */
  }

  .excel-table tr:hover {
    background-color: #e5e5e5;
    /* Hover effect for rows */
  }

  .small-button {
    padding: 4px 8px;
    /* Adjust padding for smaller buttons */
    font-size: 10px;
    /* Adjust font size for smaller buttons */
  }

  .small-currency {
    font-size: 80%;
    /* Adjust the percentage to your desired size */
  }
</style>
 
<script>
  document.addEventListener("DOMContentLoaded", function() {
    // Evento que se activa cuando se selecciona una carrera
    document.getElementById('carrerasrch').addEventListener('change', function() {
      const carreraId = this.value;
      const materiaSelect = document.getElementById('xmateria');

      // Limpiar el select de materias
      materiaSelect.innerHTML = '<option selected value="nones">Elegir Materia</option>';
      console.log("Datos a enviar:", {
        id_carrera: carreraId
      });

      // Hacer la solicitud AJAX para obtener las materias de la carrera seleccionada
      fetch('tutor/getsubject', {
          method: 'POST',
          body: JSON.stringify({
            id_carrera: carreraId
          }),
          headers: {
            'Content-Type': 'application/json'
          }
        })
        .then(response => response.json())
        .then(data => {
          // Llenar el select de materias con los datos obtenidos
          console.log("Respuesta de PHP:", data);
          data.forEach(subject => {
            const option = document.createElement('option');
            option.value = subject.id;
            option.textContent = subject.materia_des;
            materiaSelect.appendChild(option);
          });
        })
        .catch(error => {
          console.error('Error al obtener materias:', error);
        });

    });
  });
</script>
<h2>Perfil de Usuario</h2>  
<div class="card text-center">
  <div class="card-header">
    <ul class="nav nav-pills card-header-pills">
      <li class="nav-item">
        <a class="nav-link active" id="afic" href="#" onclick="javascript:ficha();">Ficha </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="amod" href="#" onclick="javascript:edita();">Modificar</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="hora" href="#" onclick="javascript:horario();">Horario de sesiones</a>
      </li>
    </ul>
  </div>
  <div class="card-body text-left ml-4" id="ficha" style="display: block;">
    <div class="row col-md-10 col-lg-10">
      <h5 class="card-title mr-3"> Tutor</h5>
      <div class=" col-md-4 col-lg-4  text-center mt-3 ">
        <img src="<?php if ($this->perfil['foto'] != '') {
                    echo BASE_URL . 'public/img/profiles/' . $this->perfil['foto'] . '.jpg';
                  } else {
                    echo BASE_URL . 'public/img/profiles/profile.JFIF';
                  } ?>" class="img-thumbnail" alt="...">
      </div>
      <div class=" col-md-6 col-lg-6  text-center mt-3 ">
        <h5>Datos Personales</h5>
        <table class="table table-user-information mt-3">
          <tbody>
            <tr>
              <td>Nombre:</td>
              <td><?php  echo $this->perfil['name'] . ' ' . $this->perfil['apellido']; ?></td>
            </tr>
            <tr>
              <td>Inscrito:</td>
              <td><?php echo $this->perfil['date']; ?> </td>
            </tr>
            <tr>
              <td>Cedula</td>
              <td><?php echo $this->perfil['cedula']; ?></td>
            </tr>
            <tr>
            <tr>
              <td>Email</td>
              <td><?php echo $this->perfil['email']; ?></td>
            </tr>
            <tr>
              <td>Telefono</td>
              <td><?php echo $this->perfil['telefono']; ?></td>
            </tr>
          </tbody>
        </table>

      </div>
    </div>
    <div class="row col-md-12 col-lg-12">
    <div class="col-md-4 col-lg-4   list-group text-left ml-3">
      <h5>Materias</h5>
      <ul> <?php foreach ($this->subjecttutor  as $key => $value) {
              echo  '<li>' . $value['materia_des'] . '</li>';
            } ?>
      </ul>
    </div>
    <div class="col-md-6 col-lg-6   list-group  ml-3">
    <h5 class="text-center">Experiencia</h5>
    <?php 
    if($this->perfil['about']==''){ 
      echo ' <button type="button" class="btn btn-secondary btn-sm" data-toggle="modal" data-target="#exampleModalabout">Agregar Experiencia</button>';
    }else{echo'<p>'.$this->perfil['about'].'</p> <button type="button" class="btn btn-secondary btn-sm" data-toggle="modal" data-target="#exampleModalabout">Modificar</button>';}
    ?>
      
    </div>
    </div>
    <hr></hr>
    <div class=" col-md-12 col-lg-12 text-right mt-2 ">
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal2"> Eliminar Perfil</button>
    </div>
    <div class="modal fade" id="exampleModal2" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Eliminar Perfil</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            Al eliminar el perfil, todos sus datos quedaran permanentemente borrados de la base de datos.
            Seguro desea eliminar?
            <form name="form2" method="post" action="" id="myform" enctype="multipart/form-data">
              <input type="hidden" value="<?php echo $this->perfil['id']; ?>" name="idu">
              <input type="hidden" value="<?php echo  $this->perfil['foto'] . '.jpg'; ?>" name="pic">  
              <div class="modal-footer mt-2">
                <input type="submit" class="btn btn-primary" value="Confirmar" name='elm'>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="card-body" id="edita" style="display: none;">
    <form name="form2" method="post" action="" id="myformpr" style="display:block;" enctype="multipart/form-data">
      <div class="form-group col-md-6 ">
        <h5 class="card-title">Tutor</h5>
        <img src="<?php if ($this->perfil['foto'] != '') {
                    echo BASE_URL . 'public/img/profiles/' . $this->perfil['foto'] . '.jpg';
                  } else {
                    echo BASE_URL . 'public/img/profiles/profile.JFIF';
                  } ?>" class="img-thumbnail" alt="...">

        <img id="frame"   width="220px" height="auto" class="img-fluid mb-2"  />
        <input type="file" onchange="preview()" id="file" style="visibility:hidden;" name="pic" />
        <script>
          function preview() {
            frame.src = URL.createObjectURL(event.target.files[0]);
          }
        </script>
        <label for="file" button class="btn btn-outline-dark btn-sm btn-block">Subir Foto</label>
      </div>
      <div class="form-row">
        <div class="form-group col-md-6 ">
          <label for="">Nombre(s)</label>
          <input type="text" class="form-control <?php if (isset($this->_message) and $this->_message['error'] == 1) echo 'is-invalid'; ?>" placeholder="" name="name"
            value="<?php if (isset($this->perfil)) echo $this->perfil['name']; ?>">
        </div>
        <div class="form-group col-md-6">
          <label for="">Apellido(s)</label>
          <input type="text" class="form-control <?php if (isset($this->_message) and $this->_message['error'] == 2) echo 'is-invalid'; ?>" placeholder="" name="apell"
            value="<?php if (isset($this->perfil)) echo $this->perfil['apellido']; ?>">
        </div>
      </div>
      <div class="form-row">
        <div class="form-group col-md-6">
          <label for="">Cédula</label>
          <input disabled type="text" placeholder="Introduzca C.I. EJ: V0000000000" class="form-control <?php if (isset($this->_message) and $this->_message['error'] == 3) echo 'is-invalid'; ?>" name="cedu"
            value="<?php if (isset($this->perfil)) echo $this->perfil['cedula']; ?>">
        </div>
        <div class="form-group col-md-6" id="email">
          <label for="" id='labelemail'>Email </label>
          <input disabled type="email" id="eml" class="form-control <?php if (isset($this->_message) && $this->_message['error'] == 4) echo 'is-invalid'; ?>" name="email"
            value="<?php if (isset($this->perfil)) echo $this->perfil['email']; ?>">
        </div>
      </div>
      <div class="form-group col-md-6" id="telefono">
        <label for="">Telefono</label>
        <input type="tel" id="tlf" class="form-control <?php if (isset($this->_message) and $this->_message['error'] == 6) echo 'is-invalid'; ?>" name="tlf"
          value="<?php if (isset($this->perfil)) echo $this->perfil['telefono']; ?>">
      </div> 
      <div class=" col-md-12 col-lg-12 ">
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal"> Guardar cambios</button>
      </div>
      <!-- Modal -->
      <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Confirmación</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              Seguro desea guardar los cambios?
              <div class="modal-footer mt-2"> 
              <input type="submit" class="btn btn-primary" value="Confirmar" name='med' >  
              </form>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
             </div>
            </div>
          </div>
        </div>
      </div>
    </div>
<div class="card-body text-left ml-4" id="horario" style="display: none;">
<div class=" col-md-12 col-lg-12 text-right ">
    <button type="button" class="btn btn-sm btn-primary" data-toggle="modal" data-target="#exampleModal3"> Agregar Sesion</button>
  </div>
  <div class="row col-md-10 col-lg-10">
    <div class=" col-md-12 col-lg-12  text-center mt-3 ">
      <h5>Sesiones</h5>
      <table class="col-md-12  table-bordered table-striped table-condensed cf excel-table">
        <thead>
          <tr>
            <th>Materia</th>
            <th>Dia</th>
            <th>Hora Inicial</th>
            <th>Hora Final </th>
            <th>Inscritos </th>
            <th></th>
            
          </tr>
        </thead>
        <tbody id="productTableBody">

          <?php foreach ($this->sessions  as $key => $value) {

            echo '<tr>' . '<td>' . $value['dia'] . '</td>' . '<td>' . $value['materia_des'] . '</td>' .
              '<td>' . $value['h_inicio'] . '</td>' . '<td>' . $value['h_final'] . '</td>' . 
              '<td>'.$value['inscritos'].'</td>'.'<td><button class="btn btn-outline-secondary small-button" data-toggle="modal" data-target="#edit'.$value['id_horario'].'">Modificar</button></td>'.'</tr>';
echo '<div class="modal fade" id="edit'.$value['id_horario'].'" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Modificar Horario de Sesion</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body"> 
          ';if(isset($this->modalmessage2)){echo '<div class="alert alert-danger" role="alert">'. $this->modalmessage2['msjx'].'</div>';} echo '
            <form name="form2" method="post" action="" id="myform" enctype="multipart/form-data">
              <input type="hidden" value="'. $value['id_horario'].'" name="idhora"><p class="text-left">' 
              
              . $value['materia_des'].': '.$value['dia'].' de  '.$value['h_inicio'] . '  a  ' . $value['h_final'] .'</p>
              <hr>
            <div class="form-group">
              <label for="exampleFormControlSelect1">Dia de Semana</label>
              <select class="form-control"';  if (isset($this->modalmessage) and $this->modalmessage['err'] == 2){echo "is-invalid";} echo 'id="addmateria" name="dia">
               
                <option value="Lunes"';if($value['dia']=="Lunes"){echo "selected";}echo '>Lunes</option>
                <option value="Martes"';if($value['dia']=="Martes"){echo "selected";}echo '>Martes</option>
                <option value="Miercoles"';if($value['dia']=="Miércoles"){echo "selected";}echo '>Miércoles</option>
                <option value="Jueves"';if($value['dia']=="Jueves"){echo "selected";}echo '>Jueves</option>
                <option value="Viernes"';if($value['dia']=="Viernes"){echo "selected";}echo '>Viernes</option>
                <option value="Sabado"';if($value['dia']=="Sábado"){echo "selected";}echo '>Sábado</option>
              </select>
            </div>
            <div class="form-row">
              <div class="form-group col-4">
                <label for="exampleFormControlSelect1">Inicio</label>
                <select class="form-control"'; if (isset($this->modalmessage) and $this->modalmessage['err'] == 3) {echo "is-invalid";}echo 'id="addmateria" name="horai">
                 
                  <option value="8"';if($value['inicio']=="8"){echo "selected";}echo '>8 am</option>
                  <option value="9"';if($value['inicio']=="9"){echo "selected";}echo '>9 am</option>
                  <option value="10"';if($value['inicio']=="10"){echo "selected";}echo '>10 am</option>
                  <option value="11"';if($value['inicio']=="11"){echo "selected";}echo '>11 am</option>
                  <option value="12"';if($value['inicio']=="12"){echo "selected";}echo '>12 pm</option>
                  <option value="13"';if($value['inicio']=="13"){echo "selected";}echo '>1 pm</option>
                  <option value="14"';if($value['inicio']=="14"){echo "selected";}echo '>2 pm</option>
                  <option value="15"';if($value['inicio']=="15"){echo "selected";}echo '>3 pm</option>
                  <option value="16"';if($value['inicio']=="16"){echo "selected";}echo '>4 pm </option>
                  <option value="17"';if($value['inicio']=="17"){echo "selected";}echo '>5 pm</option>
                </select>
              </div>
              <div class="form-group col-4">
                <label for="exampleFormControlSelect1">Hasta</label>
                <select class="form-control"';if (isset($this->modalmessage) and $this->modalmessage['err'] == 4){echo "is-invalid";} echo 'id="addmateria" name="horaf">
                   
                  <option value="9"';if($value['final']=="9"){echo "selected";}echo '>9 am</option>
                  <option value="10"';if($value['final']=="10"){echo "selected";}echo '>10 am</option>
                  <option value="11"';if($value['final']=="11"){echo "selected";}echo '>11 am</option>
                  <option value="12"';if($value['final']=="12"){echo "selected";}echo '>12 pm</option>
                  <option value="13"';if($value['final']=="13"){echo "selected";}echo '>1 pm</option>
                  <option value="14"';if($value['final']=="14"){echo "selected";}echo '>2 pm</option>
                  <option value="15"';if($value['final']=="15"){echo "selected";}echo '>3 pm</option>
                  <option value="16"';if($value['final']=="16"){echo "selected";}echo '>4 pm </option>
                  <option value="17"';if($value['final']=="17"){echo "selected";}echo '>5 pm</option>
                   <option value="18"';if($value['final']=="18"){echo "selected";}echo '>6 pm</option>
                </select>
              </div>
            </div>
              <div class="modal-footer mt-2">
                <input type="submit" class="btn btn-primary" value="Confirmar" name="edithora">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>';
          } ?>

        </tbody>
      </table>
    </div>
  </div> 
  <div class="row col-md-12 col-lg-12 text-center">
    <div class=" col-md-8 col-lg-8 mt-3 text-center">
      <h5>Clases Particulares</h5> <?php //print_r($this->inscripciones);
                              ?>
      <table class="col-md-12  table-bordered table-striped table-condensed cf excel-table">
        <thead>
          <tr>
            <th>Estudiante</th>
            <th>Materia</th> 
            <th>Observaciones</th>
            <th></th>
          </tr>
        </thead>
        <tbody id="productTableBodyE">
          <?php foreach ($this->requests  as $key => $value) {
            echo '<tr>' . '<td>' . htmlspecialchars($value['nombre'], ENT_QUOTES, 'UTF-8') . '</td>' .
              '<td>' . htmlspecialchars($value['materia_des'], ENT_QUOTES, 'UTF-8'); if($value['status']==1){echo " (Cancelado)";} echo '</td>' .
               '<td>' . htmlspecialchars($value['memo'], ENT_QUOTES, 'UTF-8') . '</td>'.
              '<td><button ';if($value['status']==1){echo "disabled";}echo' class="btn btn-outline-secondary small-button" data-toggle="modal" data-target="#req'.$value['id_particulares']. '">Cancelar</button></td>' . 
             
              
              
              '<div class="modal fade" id="req'.$value['id_particulares'].'" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Canelar Solicitud</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <div class="modal-body"> 
                        Seguro desea cancelar la solicitud?
                        <form name="form2" method="post" action="" id="myformr">
                          <input type="hidden" value="'.$value['id_particulares'].'" name="reqid"> 
                          <div class="modal-footer mt-2">
                            <input type="submit" class="btn btn-primary" value="Confirmar" name="reqcan">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                          </div>
                        </form>
                      </div>
                    </div>
                  </div>
                </div>'.
              '</tr>';
          } ?>
        </tbody>
      </table>
    </div>
  </div>
  <div class="modal fade" id="exampleModal3" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header"> 
          <h5 class="modal-title" id="exampleModalLabel">Agregar sesion</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
        <?php if(isset($this->modalmessage)){echo '<div class="alert alert-danger" role="alert">'. $this->modalmessage['msjx'].'</div>';}  ?>
          <form method="post" action="" enctype="multipart/form-data">
            <!-- Button trigger modal -->

            <div class="form-group">
              <label for="exampleFormControlSelect1">Filtrar materias por carrera</label>
              <select class="form-control" id="carrerasrch">
                <option selected value="nones">Elegir Carrera</option>
                <?php foreach ($this->escuela as $key => $value) { ?>
                  <option value=<?php echo $value['id']; ?> <?php if (isset($this->perfil) and $this->perfil['id_escuela'] == $value['id']) echo 'selected'; ?>><?php echo $value['escuela']; ?></option>
                <?php } ?>
              </select>
            </div>
            <hr>
            <div class="form-group">
              <h6>Formulario de Carga de Sesiones</h6>
              <label for="exampleFormControlSelect1">Materia</label>
              <select class="form-control <?php if (isset($this->modalmessage) and $this->modalmessage['err'] == 1) echo 'is-invalid'; ?>" id="xmateria" name="materia" >
                <option selected value="nones">Elegir Materia</option>
                <?php foreach ($this->subject  as $key => $value) {
                  echo  "<option value=".  $value['id'] . '>' . $value['materia_des'] . '</option>';
                } ?>

              </select>
            </div>
            <div class="form-group">
              <label for="exampleFormControlSelect1">Dia de Semana</label>
              <select class="form-control <?php if (isset($this->modalmessage) and $this->modalmessage['err'] == 2) echo 'is-invalid'; ?>" id="addmateria" name="dia">
                <option selected value="0">Elegir Dia</option>
                <option value="Lunes">Lunes</option>
                <option value="Martes">Martes</option>
                <option value="Miercoles">Miercoles</option>
                <option value="Jueves">Jueves</option>
                <option value="Viernes">Viernes</option>
                <option value="Sabado">Sabado</option>
              </select>
            </div>
            <div class="form-row">
              <div class="form-group col-4">
                <label for="exampleFormControlSelect1">Inicio</label>
                <select class="form-control <?php if (isset($this->modalmessage) and $this->modalmessage['err'] == 3) echo 'is-invalid'; ?>" id="addmateria" name="horai">
                  <option selected value="0">Elegir Hora</option>
                  <option value="8">8 am</option>
                  <option value="9">9 am</option>
                  <option value="10">10 am</option>
                  <option value="11">11 am</option>
                  <option value="12">12 pm</option>
                  <option value="13">1 pm</option>
                  <option value="14">2 pm</option>
                  <option value="15">3 pm</option>
                  <option value="16">4 pm </option>
                  <option value="17">5 pm</option>
                </select>
              </div>
              <div class="form-group col-4">
                <label for="exampleFormControlSelect1">Hasta</label>
                <select class="form-control <?php if (isset($this->modalmessage) and $this->modalmessage['err'] == 4) echo 'is-invalid'; ?>" id="addmateria" name="horaf">
                  <option selected value="0">Elegir Hora</option>
                  <option value="8">8 am</option>
                  <option value="9">9 am</option>
                  <option value="10">10 am</option>
                  <option value="11">11 am</option>
                  <option value="12">12 pm</option>
                  <option value="13">1 pm</option>
                  <option value="14">2 pm</option>
                  <option value="15">3 pm</option>
                  <option value="16">4 pm </option>
                  <option value="17">5 pm</option>
                  <option value="18">6 pm</option>
                </select>
              </div>
            </div>
            <hr>
            </hr>
            <div class="modal-footer mt-2">
              <input type="submit" class="btn btn-primary" value="Agregar" name='addhro'>
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="exampleModalabout" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Mi Expeirencia</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body"> 
            <form name="form2" method="post" action="" id="myformabt" enctype="multipart/form-data">
              <input type="hidden" value="<?php echo $this->perfil['id']; ?>" name="idtut">
              <textarea class="form-control" aria-label="With textarea" name=about rows="10"><?php echo $this->perfil['about'];?></textarea>
              <div class="modal-footer mt-2">
                <input type="submit" class="btn btn-primary" value="Confirmar" name='abt'>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
</div>



<?php if (Session::accessViewStrict(array('user'))): ?>
  <p><a href="<?php BASE_URL; ?>post/add">Add a Post</a></p>
<?php endif; ?>
<script type="text/javascript">
  function ficha() {
    document.getElementById('edita').style.display = 'none';
    document.getElementById('horario').style.display = 'none';
    document.getElementById('ficha').style.display = 'block';
    document.querySelector('.nav-link[onclick="javascript:ficha();"]').classList.add('active');
    document.querySelector('.nav-link[onclick="javascript:edita();"]').classList.remove('active');
    document.querySelector('.nav-link[onclick="javascript:horario();"]').classList.remove('active');
  }

  function edita() {
    document.getElementById('edita').style.display = 'block';
    document.getElementById('horario').style.display = 'none';
    document.getElementById('ficha').style.display = 'none';
    document.querySelector('.nav-link[onclick="javascript:ficha();"]').classList.remove('active');
    document.querySelector('.nav-link[onclick="javascript:edita();"]').classList.add('active');
    document.querySelector('.nav-link[onclick="javascript:horario();"]').classList.remove('active');

  }

  function horario() {
    document.getElementById('edita').style.display = 'none';
    document.getElementById('ficha').style.display = 'none';
    document.getElementById('horario').style.display = 'block';
    document.querySelector('.nav-link[onclick="javascript:ficha();"]').classList.remove('active');
    document.querySelector('.nav-link[onclick="javascript:edita();"]').classList.remove('active');
    document.querySelector('.nav-link[onclick="javascript:horario();"]').classList.add('active');


  }


  function registok() {
    document.getElementById("myform").style.display = "block";
    document.getElementById("success").style.display = "block";
  }
</script>