<h2 class="mb-4">Iniciar Sesion</h2>
<form method="post" action="">
  <div class="form-group row">
    <label for="inputEmail3" class="col-sm-2 col-form-label">Email</label>
    <div class="col-sm-10">
      <input type="email" class="form-control" id="inputEmail3" name="email">
    </div>
  </div>
  <div class="form-group row">
    <label for="inputPassword3" class="col-sm-2 col-form-label">Password</label>
    <div class="col-sm-10">
      <input type="password" class="form-control" id="inputPassword3" name="pass">
    </div>
  </div> 
  <div class="form-group row">
    <div class="col-sm-10">
    <input type="submit" class="btn btn-primary" value="Enviar" name="sendx"> 
    </div>
  </div>
</form> 